logging:
  level:
    root: debug

spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache.use_second_level_cache: false
        default_batch_fetch_size: 20
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

#  devtools:
#    livereload:
#      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  # Static resources reloading during development
  profiles:
    active: dev
