POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGpsZWUtY2xpZW50OnRqbGVlLXNlY3JldA==

username=tjlee0&password=tjlee0&grant_type=password

### 암호 부여 유형(password)은 자사 클라이언트가 사용자의 자격 증명을 액세스 토큰으로 교환하는 데 사용됩니다.
### 여기에는 클라이언트에게 사용자에게 암호를 요구하는 것이 포함되므로 타사 클라이언트가 암호를 사용해서는 안됩니다.
### 이 흐름에서 사용자의 사용자 이름과 비밀번호는 액세스 토큰과 직접 교환됩니다.