POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGpsZWUtY2xpZW50OnRqbGVlLXNlY3JldA==

grant_type=client_credentials

### 클라이언트 신임 정보 부여 유형은 클라이언트가 사용자 컨텍스트 외부에서 액세스 토큰을 얻는 데 사용됩니다.
### 이것은 일반적으로 클라이언트가 사용자의 리소스에 액세스하기보다는 자신에 대한 리소스에 액세스하는 데 사용됩니다.
###